-- ─────────────────────────────────────────────────────────────────────────────
-- EXTENDED INVENTORY & MODIFIER SCHEMA FOR SUPABASE
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Create ingredients table
CREATE TABLE IF NOT EXISTS public.ingredients (
    id bigint PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    name text NOT NULL,
    unit text DEFAULT 'g',
    current_stock numeric DEFAULT 0,
    reorder_level numeric DEFAULT 100,
    cost_per_unit numeric DEFAULT 0,
    supplier_id bigint REFERENCES public.suppliers(id),
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    deleted_at timestamptz
);

-- 2. Create recipes table
CREATE TABLE IF NOT EXISTS public.recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    product_id bigint NOT NULL,
    ingredient_id bigint NOT NULL REFERENCES public.ingredients(id),
    quantity numeric NOT NULL,
    unit text,
    updated_at timestamptz DEFAULT now(),
    UNIQUE(tenant_id, product_id, ingredient_id)
);

-- 3. Create modifiers table
CREATE TABLE IF NOT EXISTS public.modifiers (
    id bigint PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    is_required boolean DEFAULT false,
    allow_multiple boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 4. Create modifier_options table
CREATE TABLE IF NOT EXISTS public.modifier_options (
    id bigint PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    modifier_id bigint NOT NULL REFERENCES public.modifiers(id) ON DELETE CASCADE,
    name text NOT NULL,
    price_adjustment numeric DEFAULT 0,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 5. Create product_modifiers link table
CREATE TABLE IF NOT EXISTS public.product_modifiers (
    tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    product_id bigint NOT NULL,
    modifier_id bigint NOT NULL REFERENCES public.modifiers(id) ON DELETE CASCADE,
    PRIMARY KEY (tenant_id, product_id, modifier_id)
);

-- 6. Enable RLS
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.modifier_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_modifiers ENABLE ROW LEVEL SECURITY;

-- 7. RLS Policies
DROP POLICY IF EXISTS "Ingredients: Tenant Isolation" ON public.ingredients;
CREATE POLICY "Ingredients: Tenant Isolation" ON public.ingredients
FOR ALL TO anon USING (tenant_id = public.get_tenant_id()) WITH CHECK (tenant_id = public.get_tenant_id());

DROP POLICY IF EXISTS "Recipes: Tenant Isolation" ON public.recipes;
CREATE POLICY "Recipes: Tenant Isolation" ON public.recipes
FOR ALL TO anon USING (tenant_id = public.get_tenant_id()) WITH CHECK (tenant_id = public.get_tenant_id());

DROP POLICY IF EXISTS "Modifiers: Tenant Isolation" ON public.modifiers;
CREATE POLICY "Modifiers: Tenant Isolation" ON public.modifiers
FOR ALL TO anon USING (tenant_id = public.get_tenant_id()) WITH CHECK (tenant_id = public.get_tenant_id());

DROP POLICY IF EXISTS "ModifierOptions: Tenant Isolation" ON public.modifier_options;
CREATE POLICY "ModifierOptions: Tenant Isolation" ON public.modifier_options
FOR ALL TO anon USING (tenant_id = public.get_tenant_id()) WITH CHECK (tenant_id = public.get_tenant_id());

DROP POLICY IF EXISTS "ProductModifiers: Tenant Isolation" ON public.product_modifiers;
CREATE POLICY "ProductModifiers: Tenant Isolation" ON public.product_modifiers
FOR ALL TO anon USING (tenant_id = public.get_tenant_id()) WITH CHECK (tenant_id = public.get_tenant_id());
